openapi: 3.0.1
info:
  title: User Management API
  description: API for managing users in a system.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: "Servidor local"
paths:
  /hello:
    get:
      tags:
        - serviceordermanagement-controller
      description: Lista de requerimientos
      operationId: searchRequirements
      summary: Get message hello world
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: string
        '429':
          description: Too Many Requests - Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Too many requests. Please try again later."
        errorCode:
          type: integer
          example: 429


